### ISSUE TITLE
Does not work with recent WhatsApp

### ISSUE THREAD

**Issue by andybalaam** [MichaelAquilina/Whatsappium#1]
This plugin does not work with recent versions of WhatsApp.  The fork here does.  I am working on porting the fixes from there.

**Comment by MichaelAquilina** [comment]
Thanks for opening the Issue and a PR @andybalaam . It is true that I have not been keeping an eye on this repo for a while so it is perfectly possible things have broken :)

**Comment by andybalaam** [comment]
np, thanks for the useful plugin!
